### ISSUE TITLE
Automated tests to check thickness units

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6-examples#139]
Previous work introduced a thickness (H) unit. This made it possible to test for errors in expressions involving thickness by setting the H to different powers-of-two in two runs and then comparing the output of these runs. If the output is the same in both then a class of errors can be ruled out.

This issue will create a repeatable automated test based on the above work. Further work will extend this issue to cope with additional units.

**Comment by marshallward** [comment]
I think we can call this resolved now that Bob's huge scaling project has been completed, and the test suite is now active.
