### ISSUE TITLE
transport on potential density surfaces

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#154]
For CMIP6, we need to diagnose horizontal transport on sigma2000.  Are we ready to exercise the regridding routine to do this?

**Comment by adcroft** [comment]
Is this needed for monthly or just annual?

**Comment by adcroft** [comment]
Also, I'm going to use _rho2 suffix for the file names, unless that's been set by CMIP?

**Comment by StephenGriffies** [comment]
monthly is needed.

Name for the file names are not specified.

**Comment by StephenGriffies** [comment]
monthly is needed for all overturning transport diagnostics, including GM and submeso.

**Comment by adcroft** [comment]
We need to decide on range and resolution for density space diagnostics...

**Comment by StephenGriffies** [comment]
This is what we used in MOM5 for years, based on rho2000.  It likely is sufficient for our OM4 simulations.  The delta(rho) are evenly spaced into 80 layers. 

 &ocean_density_nml
	potrho_min=1028.0
	potrho_max=1038.0
	layer_nk=80

**Comment by adcroft** [comment]
Actually, I was thinking about reducing it to fewer levels for the sake of
space. This is monthly output.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by StephenGriffies** [comment]
My concern with reducing the density classes is that we will miss the subtle issues related to deep overturning cells.  To capture these cells with a uniform delta(rho) generally requires many layers.  If you wish to test nonlinear delta(rho), that may be fruitful, but it will take some testing.  

If archive space is an issue (when is it not), I would strongly prefer annual means for all of the overturning diagnostics, keeping no less than 80 delta(rho) bins.  I do not think it wise to coarsen in density class space without testing.

**Comment by jkrasting** [comment]
@StephenGriffies, @adcroft - Is there any sample output that you can point me to for testing?
