### ISSUE TITLE
areacello regridding is wrong

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#155]
We should regrid areacello to the 1x1 grid using a different flag.

**Comment by adcroft** [comment]
Can you explain what you mean by "different flag"?

**Comment by StephenGriffies** [comment]
This comes from JPD.  He said it should be interpolated extensive rather than intensive (I think...?).  My recollection is that this choice is set by a flag.  Hence my "other flag" request.  JPD may need to be consulted to be sure...
