### ISSUE TITLE
tos \ne thetao[k=1]

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#159]
In Huan Guo's 5yr test run for CMIP6, we have 

thetao[k=1]  \ne tos

The differences are significant.  What is the cause for the difference?  We need to be sure to have self-consistency for these two fields.  That is critical for the CMIP6 submission.

**Comment by adcroft** [comment]
Anyone have thoughts on this issue?

**Comment by ashao** [comment]
I'll look into it tomorrow.

**Comment by MJHarrison-GFDL** [comment]
tos is the top level temperature in native mode whereas thetao[k=1] is remapped to the Levitus grid, so it's a difference in the vertical extent of these two fields

**Comment by ashao** [comment]
Slight correction to @MJHarrison-GFDL: 'tos' is temperature averaged over a depth determined by the runtime-parameter HMIX_SFC_PROP (set to 1.0m in OM4_025 and OM4_05). The top level of the vertical coordinate is nominally 2m and the diagnostic is done after the ALE step, so for all practical purposes Matt is correct. Probably more importantly, 'tos' is the same field that is reported to the coupler as SST.

**Comment by ashao** [comment]
Relevant lines:
https://github.com/NOAA-GFDL/MOM6/blob/776212307ae15b17fb48ead11c89fdffd5b9830d/src/core/MOM.F90#L3538-L3579

**Comment by StephenGriffies** [comment]
I am looking at the ocean_annual output, so thetao[k=1] is the native grid output.  So there is no issue with regridding to Levitus. 

Am I missing something?

**Comment by adcroft** [comment]
The mystery is why a sub-sample of the top layer (reported as `tos`) is not the same as `thetao(k=1)` from ocean_annual.

`thetao(k=1)` from ocean_annual_z is an average of the top 2.5m of the model and will not match `tos`.

**Comment by ashao** [comment]
I think what it boils down to is that the post_data for thetao and post_data for tos are not called with the same frequency within the code. post_data for thetao is done iff (CS%t_dyn_rel_adv == 0.0) whereas tos is posted every time that step_MOM is called.

**Comment by adcroft** [comment]
@ashao Nice hypothesis: so DT_FORCING!=DT_THERM is the cause.

**Comment by StephenGriffies** [comment]
Is there a good reason to not call the diags on the same times?  I can see confusion (beyond mine) with the subtle distinction between tos and theta[k=1].  Furthermore, what sets the magnitude of the distinction?  Could a model with very heavy eddy activity show more differences?

**Comment by Hallberg-NOAA** [comment]
Theta is being called every time the ocean thermodynamics are
      up-to-date, which might span coupled timesteps. By contrast, TOS
      is needed every time-step for coupling to the atmosphere and
      sea-ice, and must be calculated at the end of every coupled
      timestep. The temperatures in TOS do not change from step to step,
      but the thicknesses that are being used in the vertical average
      do. Whether there is some separate diagnostic for TOS that is only
      sent at the same (lower or higher) frequency as theta[k=1] is a
      different matter. Mesoscale eddy activity probably has very little
      to do with these differences - mostly the differences arise from
      an aliasing of the diurnal cycle.
    
    On 09/22/2017 01:32 PM, Stephen
      Griffies wrote:
    
    
      Is there a good reason to not call the diags on the same times?
        I can see confusion (beyond mine) with the subtle distinction
        between tos and theta[k=1]. Furthermore, what sets the magnitude
        of the distinction? Could a model with very heavy eddy activity
        show more differences?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NOAA-GFDL/MOM6-examples","title":"NOAA-GFDL/MOM6-examples","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NOAA-GFDL/MOM6-examples"}},"updates":{"snippets":[{"icon":"PERSON","message":"@StephenGriffies in #159: Is there a good reason to not call the diags on the same times?  I can see confusion (beyond mine) with the subtle distinction between tos and theta[k=1].  Furthermore, what sets the magnitude of the distinction?  Could a model with very heavy eddy activity show more differences?   "}],"action":{"name":"View Issue","url":"https://github.com/NOAA-GFDL/MOM6-examples/issues/159#issuecomment-331511449"}}}

**Comment by StephenGriffies** [comment]
Good points.  Can we include this discussion in a streamlined form within the code where tos is diagnosed?  Just a comment in the code, nothing more.  

Doing so will greatly reduce confusion in the future.

**Comment by adcroft** [comment]
This issue affects all variables. eta_bt, v, T_predia each are posted at different frequencies within the code.

I'm not sure how adding a comment in the code helps - the frequency seen in diagnostics is external to the model and the issue is a function of the combination of time-steps.

**Comment by adcroft** [comment]
Hopefully NOAA-GFDL/MOM6#611 is a good enough solution for this issue ... I've flagged @StephenGriffies as the reviewer.
