### ISSUE TITLE
salt_flux diagnostic identically zero in CM4

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#16]
The diagnostic field "salt_flux" is identically zero in the CM4 simulations.  This field should be nonzero, as it represents the transfer of salt between the liquid ocean and solid sea ice.  There is either a problem with the diagnostic or a problem with the prognostic model.  This issue should be high priority to debug, as the bug could cause major problems in sea ice regions if there is no salt exchanged between liquid and solid.

**Comment by adcroft** [comment]
I've just checked that salt_flux is not zero in CM4 + SIS2 (for which we did not set the sea-ice salinity to zero). The pattern even looks sensible! :+1:

![salt_flux_cm4_sis2_yrs61-80](https://cloud.githubusercontent.com/assets/5859571/9260983/14fd5b04-41d9-11e5-8077-73e57030458d.png)
