### ISSUE TITLE
Z-ouput has wrong missing value

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6-examples#160]
In the CMIP6 test run, the MOM6 missing values are incorrect.  The MOM6 output has _FillValue= -1.e+34.  The CMOR missing value should be 1.e+20.

**Comment by ashao** [comment]
I  had previously added a DIAG_MISVAL runtime flag. I've used it to change
the value from -1.e34 to 0.0.

**Comment by adcroft** [comment]
Thanks @ashao . Since the 1.e34 is arbitrary, I'll change the default to the CMOR value.

**Comment by adcroft** [comment]
@jkrasting  I've changed this (in NOAA-GFDL/MOM6#594) but why is there a CMOR requirement for the missing value? In principle there's no need for it to be the same between files or variables so long as it's in the attributes. Can you give the reference?

**Comment by jkrasting** [comment]
@adcroft, see CMIP5 specifications in [Taylor et al. 2010](http://cmip-pcmdi.llnl.gov/cmip5/docs/CMIP5_output_metadata_requirements.pdf), page 12.

> "All "missing data" must be assigned the single precision floating point value of 1.e20"

**Comment by ashao** [comment]
@adcroft, @jkrasting: Just to clarify, I meant that I had changed it for my
own purposes to 0.0. It seemed to work as intended for both native and
remapped output.
