### ISSUE TITLE
Incorrect CMOR units string

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6-examples#165]
"kg/s" is not a valid CMOR units string.  Slashes, in general, are incompatible.

We need scan the availalable_diags file and replace "kg/s" with "kg s-1".

**Comment by adcroft** [comment]
For reference, http://clipc-services.ceda.ac.uk/dreq/index/units.html

We have a mix of units style throughout the code. e.g. "meter", "meters", "m", "m-2", "meter-2", "/m2.". Anyone foresee a problem if I just unilaterally change all units to be compliant?

**Comment by StephenGriffies** [comment]
I see no problem.  Thanks for this.  And sorry, as most of the errors are likely from me.

**Comment by jkrasting** [comment]
No problem here, either.

**Comment by adcroft** [comment]
585 edits later, our 1580 diagnostics are down to 54 combinations of CMIP6-style units (down from 101). I think I have them all with three exceptions:
- "none" and "nondim" should be "unitless" according to CMIP6. I'm going to do this using cmor_units= since for some units they should in fact be things like "m m-1" or "kg kg-1".
- "mg m-3" for Chl since it's what we use and I'm not sure what the units should be.

Here's the list of our new units (after NOAA-GFDL/MOM6#610 is accepted):
```bash
% fgrep units available_diags.000000  | sort | uniq
    ! units: %
    ! units: N m-2
    ! units: Pa
    ! units: W
    ! units: W m-2
    ! units: degC
    ! units: degC kg m-2
    ! units: degC m s-1
    ! units: degC m3 s-1
    ! units: degC s-1
    ! units: degC2
    ! units: degC2 s-1
    ! units: degrees_east
    ! units: degrees_north
    ! units: kg
    ! units: kg m-2
    ! units: kg m-2 s-1
    ! units: kg m-3
    ! units: kg s-1
    ! units: m
    ! units: m m-1
    ! units: m s-1
    ! units: m s-2
    ! units: m s2
    ! units: m-1
    ! units: m-1 s-1
    ! units: m-1 s-2
    ! units: m2
    ! units: m2 s-1
    ! units: m2 s-2
    ! units: m2 s-3
    ! units: m3
    ! units: m3 s-1
    ! units: m3 s-3
    ! units: m4 s-1
    ! units: mg m-3
    ! units: nondim
    ! units: none
    ! units: psu
    ! units: psu kg m-2
    ! units: psu m s-1
    ! units: psu m-2 s-1
    ! units: psu m3 s-1
    ! units: psu s-1
    ! units: psu2 s-1
    ! units: s
    ! units: s-1
    ! units: s-2
    ! units: s2 m
    ! units: tracer concentration * m-2 s-1
    ! units: tracer concentration * s-1
    ! units: tracer content * m-2 s-1
    ! units: yr
    ! units: yr m3 s-1
```

**Comment by jkrasting** [comment]
Wow! What an effort!! This is great!
-- 
-----
Dr. John Krasting, Physical Scientist
Biogeochemistry, Ecosystems, and Climate Group
NOAA/Geophysical Fluid Dynamics Laboratory
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by StephenGriffies** [comment]
Really good.  Thanks.
