### ISSUE TITLE
omldamax needed for OM4 diag tables

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#169]
We need to add the following line to the OM4 diag table to satisfy the requests for CMIP6

 "ocean_model", "ePBL_h_ML", "omldamax", "ocean_daily", "all", "max", "none",2

**Comment by StephenGriffies** [comment]
We need to add the following line to the OM4 diag table to satisfy the requests for CMIP6

"ocean_model", "ePBL_h_ML", "omldamax", "ocean_daily", "all", "max", "none",2

**Comment by adcroft** [comment]
I assume you mean the diag_table.MOM6 which is used for the deck?
diag_table.OM4 is additional variables which are only registered in the ice-ocean configuration for OMIP.

**Comment by StephenGriffies** [comment]
You are correct, diag_table.MOM6 is where this needs to go.  It is needed for the DECK.
