### ISSUE TITLE
straits output changed to months in OM4_025/diag_table.MOM6

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#176]
We are saving daily output for the straits data

# Sections for CMIP6/OMIP
"ocean_Barents_opening",         1, "days",   1, "days", "time"
"ocean_Bering_Strait",           1, "days",   1, "days", "time"
"ocean_Davis_Strait",            1, "days",   1, "days", "time"
"ocean_Windward_Passage",        1, "days",   1, "days", "time"
"ocean_Denmark_Strait",          1, "days",   1, "days", "time"
"ocean_Drake_Passage",           1, "days",   1, "days", "time"
"ocean_English_Channel",         1, "days",   1, "days", "time"
"ocean_Faroe_Scotland",          1, "days",   1, "days", "time"
"ocean_Florida_Bahamas",         1, "days",   1, "days", "time"
"ocean_Fram_Strait",             1, "days",   1, "days", "time"
"ocean_Iceland_Faroe_V",         1, "days",   1, "days", "time"
"ocean_Iceland_Faroe_U",         1, "days",   1, "days", "time"
"ocean_Indonesian_Throughflow",  1, "days",   1, "days", "time"
"ocean_Mozambique_Channel",      1, "days",   1, "days", "time"
"ocean_Pacific_undercurrent",    1, "days",   1, "days", "time"
"ocean_Taiwan_Luzon",            1, "days",   1, "days", "time"
"ocean_Agulhas_section",         1, "days",   1, "days", "time"
"ocean_Gibraltar_Strait",        1, "days",   1, "days", "time"
"ocean_Iceland_Norway", 1, "days", 1, "days", "time"

CMIP6 wants months.  Hence, we should change the above first instance of "days" to "months".  

# Sections for CMIP6/OMIP
"ocean_Barents_opening",         1, "months",   1, "days", "time"
"ocean_Bering_Strait",           1, "months",   1, "days", "time"
"ocean_Davis_Strait",            1, "months",   1, "days", "time"
"ocean_Windward_Passage",        1, "months",   1, "days", "time"
"ocean_Denmark_Strait",          1, "months",   1, "days", "time"
"ocean_Drake_Passage",           1, "months",   1, "days", "time"
"ocean_English_Channel",         1, "months",   1, "days", "time"
"ocean_Faroe_Scotland",          1, "months",   1, "days", "time"
"ocean_Florida_Bahamas",         1, "months",   1, "days", "time"
"ocean_Fram_Strait",             1, "months",   1, "days", "time"
"ocean_Iceland_Faroe_V",         1, "months",   1, "days", "time"
"ocean_Iceland_Faroe_U",         1, "months",   1, "days", "time"
"ocean_Indonesian_Throughflow",  1, "months",   1, "days", "time"
"ocean_Mozambique_Channel",      1, "months",   1, "days", "time"
"ocean_Pacific_undercurrent",    1, "months",   1, "days", "time"
"ocean_Taiwan_Luzon",            1, "months",   1, "days", "time"
"ocean_Agulhas_section",         1, "months",   1, "days", "time"
"ocean_Gibraltar_Strait",        1, "months",   1, "days", "time"
"ocean_Iceland_Norway",          1, "months",   1, "days", "time"

Otherwise, we need to write postprocessing code to properly handle the monthly averages, which seems unnecessary and will take more debugging time than we have now.  I see no reason to keep daily output when CMIP6 wants months.  

Andrew Shao is writing the refineDiag script assuming we will have monthly output.  Please make the change to the diag table accordingly.

**Comment by adcroft** [comment]
Isn't there a one-line xml entry to produce the monthly from daily?

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by StephenGriffies** [comment]
For other diagnostics, we are relying on the diag_table.  

Why do we need to have dailies for the straits switched to monthlies in the xml rather than making the change in the diag_table?

**Comment by adcroft** [comment]
Yes, we have current analysis based on daily output, even though not requested in CMIP6. Rather than add both daily and monthly entries in the diag_table, it is simplest to use one line in the XML as requested earlier.

**Comment by jkrasting** [comment]
Whatever we had in the 2017.09.27 tag works, so please don't make any
changes to the diag_table for the straits at this point!

**Comment by adcroft** [comment]
Meaning we got monthlies in post-processing?

>

**Comment by jkrasting** [comment]
No, dailies.  This is what works for the refine scripts that compute mfo:

ncdump -h  00010101.ocean_Denmark_Strait.nc
netcdf 00010101.ocean_Denmark_Strait { // format variant: 64bit
dimensions:
xh_sub01 = 91 ;
yh_sub01 = 1 ;
z_l = 35 ;
z_i = 36 ;
time = UNLIMITED ; // (365 currently)
nv = 2 ;
yq_sub01 = 1 ;
