### ISSUE TITLE
FMS bugs?

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6-examples#184]
Hi,

I encountered this problem when re-compiling MOM6 after merging my branch with dev/gfdl as well as dev/master (the merging was successful, after solving some conflicts):

> ../../../../src/MOM6/src/framework/MOM_time_manager.F90(19): error #6580: Name in only-list does not exist.   [GET_EXTERNAL_FIELD_AXES]
use time_interp_external_mod, only : get_external_field_axes, get_external_field_missing
-------------------------------------^
../../../../src/MOM6/src/framework/MOM_time_manager.F90(19): error #6580: Name in only-list does not exist.   [GET_EXTERNAL_FIELD_MISSING]
use time_interp_external_mod, only : get_external_field_axes, get_external_field_missing
--------------------------------------------------------------^
../../../../src/MOM6/src/framework/MOM_time_manager.F90(34): error #6404: This name does not have a type, and must have an explicit type.   [GET_EXTERNAL_FIELD_AXES]
public :: get_external_field_axes
----------^
../../../../src/MOM6/src/framework/MOM_time_manager.F90(35): error #6404: This name does not have a type, and must have an explicit type.   [GET_EXTERNAL_FIELD_MISSING]
public :: get_external_field_missing
----------^
compilation aborted for ../../../../src/MOM6/src/framework/MOM_time_manager.F90 (code 1)

What weird about this is that these problems only have to do with the MOM_time_manager.F90 script, which I did not touch either before or after the merging process. Therefore, I suspect there to be some bugs in the most updated dev/gfdl or dev/master branch. I'm wondering if people from GFDL would be willing to take a look at this issue?

Really appreciate it,

Hailu

**Comment by kshedstrom** [comment]
This has to do with a change that was made to FMS. FMS needs to be
recompiled once you make sure you are pointing to the correct version: FMS
@ c2cfbd3
<https://github.com/NOAA-GFDL/FMS/tree/c2cfbd3911c01416a703f8cc9bfa47c7846ae293>
The Makefile I use doesn't know to recompile FMS, so I had to go wipe out
the old build directory.

Kate

**Comment by MJHarrison-GFDL** [comment]
Yes. This is a problem with mkmf where it doesn't resolve the FMS library dependencies correctly.

**Comment by hlkong** [comment]
Interesting, because after I redownloaded FMS and everything and tried to recompile, I got loads of errors at the last step of compiling. For example, 

> MOM_regridding.o: In function `mom_regridding_mp_check_grid_def_':
/project/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/ALE/MOM_regridding.F90:699: undefined reference to `netcdf_mp_nf90_open_'

> MOM_diag_to_Z.o: In function `mom_diag_to_z_mp_get_z_depths_':
/project/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/diagnostics/MOM_diag_to_Z.F90:1156: undefined reference to `netcdf_mp_nf90_open_'

> `mom_shared_initialization_mp_apply_topography_edits_from_file_':
/project/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/initialization/MOM_shared_initialization.F90:199: undefined reference to `netcdf_mp_nf90_open_'

> MOM_shared_initialization.o: In function `mom_shared_initialization_mp_initialize_topography_from_file_':
/project/mfj/Hailu/MOM6/build/intel/ocean_only/repro/../../../../src/MOM6/src/initialization/MOM_shared_initialization.F90:199: undefined reference to `netcdf_mp_nf90_open_'

to mention only a few... does this mean the FMS version I downloaded (from branch dev/gfdl) still has some bugs?

**Comment by MJHarrison-GFDL** [comment]
It looks like your are missing libnetcdf.so in your PATH.

**Comment by kshedstrom** [comment]
You are actually missing libnetcdff.so, which got split out from libnetcdf a few years back. Wherever you mention -lnetcdf in the build, add a -lnetcdff.

**Comment by hlkong** [comment]
Thank you all so much for your help! Yes, it seems a -lnetcdff command is missing in the file of ncrc-intel.mk, which originally appears to be

`ifneq ($(findstring netcdf-4.0.1,$(LOADEDMODULES)),)
  LIBS += -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lz
else
  LIBS += -lnetcdf
endif`

which means only for netcdf-4.0.1 will -lnetcdff be automatically added. It seems for netcdf prior to version 4 -lnetcdff is incorporated as part of -lnetcdf, as @kshedstrom mentioned, while since netcdf 4 was released, they become split...
