### ISSUE TITLE
Diapycnal velocity (wd) not being registered

### ISSUE THREAD

**Issue by suyashbire1** [NOAA-GFDL/MOM6-examples#250]
On the `dev/master` branch, in DOME and BFB `wd` is not being registered although `ADIABATIC=False`. Other diapycnal diagnostics output fine. I get this warning when trying to output it: 
```
WARNING from PE     0: diag_util_mod::opening_file: module/field_name (ocean_model/wd) NOT registered
```

This can be reproduced using this minimal `diag_table` with DOME:
```
"MOM Experiment"
1 1 1 0 0 0
"cont_%4yr_%3dy",     1,"days",1,"days","Time",1,"days"
"mom_%4yr_%3dy",      1,"days",1,"days","Time",1,"days"

"ocean_model","dhdt","dhdt","cont_%4yr_%3dy","all",.true.,"none",2
"ocean_model","wd","wd","cont_%4yr_%3dy","all",.true.,"none",2
"ocean_model","uh","uh","cont_%4yr_%3dy","all",.true.,"none",2
"ocean_model","vh","vh","cont_%4yr_%3dy","all",.true.,"none",2

"ocean_model","dudt_dia","dudt_dia","mom_%4yr_%3dy","all",.true.,"none",2
"ocean_model","dvdt_dia","dvdt_dia","mom_%4yr_%3dy","all",.true.,"none",2
```

Is this a bug?

**Comment by suyashbire1** [comment]
There was a missing `register_diag_field` call in `MOM_diabatic_driver.F90`.

```
  CS%id_wd = register_diag_field('ocean_model','wd',diag%axesTI,Time, &
      'Diapycnal velocity', 'm s-1')
```
Was this by design? I see that the part of the code that references `id_wd` has been moved into `legacy_diabatic` subroutine. Are we not supposed to used `wd` anymore? Should we be using some combination of `ea` and `eb` instead?

**Comment by Hallberg-NOAA** [comment]
I believe that the register_diag_field call for wd was removed by mistake, and that it should be restored, at least when MOM6 is being used in a non-ALE mode.

  This change was introduced with commit https://github.com/NOAA-GFDL/MOM6/commit/4c36f8f9f , in a PR from @gustavo-marques. @gustavo-marques, would you be willing to please comment on this, and whether you agree that this call to register wd should be restored when MOM6 is in non-ALE mode?

**Comment by gustavo-marques** [comment]
@suyashbire1, I've added the missing code needed to diagnose wd - please see https://github.com/NOAA-GFDL/MOM6/pull/865 
Thanks again for letting us know about this bug.

**Comment by suyashbire1** [comment]
@Hallberg-NOAA @gustavo-marques Thank you for fixing this issue. I'll close it now.
