### ISSUE TITLE
Tests failing on obsolete flag

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6-examples#272]
From the stderr file for ocean_only/CVmix_SCM_tests/mech_only/BML:

```
FATAL: MOM_obsolete_params: Z_OUTPUT_GRID_FILE is an obsolete run-time flag, and should not be used.
```
Same for ocean_only/CVmix_SCM_tests/skin_warming_wind/BML while
ocean_only/single_column/BML fails with:
```
FATAL: MOM_obsolete_params: MIN_Z_DIAG_INTERVAL is an obsolete run-time flag, and should not be used.
```

**Comment by adcroft** [comment]
You need to update MOM6-examples following PR #271. Or if you are running your own repository of experiments then you should remove the parameters associated with the module MOM_diag_to_Z which has been obsoleted. As you noted, I think these are just the parameters "Z_OUTPUT_GRID_FILE" and "MIN_Z_DIAG_INTERVAL".

See also NOAA-GFDL/MOM6#930

**Comment by kshedstrom** [comment]
Yes, fixed now, thanks.
