### ISSUE TITLE
bug in heat transport masking?

### ISSUE THREAD

**Issue by raphaeldussin** [NOAA-GFDL/MOM6-examples#286]
https://github.com/NOAA-GFDL/MOM6-examples/blob/2ba372d642b1e7fe01bed15b927e0d7627c26cf7/tools/analysis/refineDiag_ocean_month.py#L53

this collapses lat into an empty array, resulting in the following error:

IndexError: Inconsistent shape between the condition and the input (got (12, 0) and (12, 1080))

removing it works fine. Is there a reason for this call to tile? @jkrasting @adcroft

**Comment by raphaeldussin** [comment]
@jkrasting numpy version in gfdl's python module is 1.11.0b3 and does not crash on bad line but do not mask the latitudes south of 34S, version 1.16.4 crashes. @StephenGriffies might be interested about it.

My take is that this line should be removed to assure forward compatibility since it does not seem to be effective. If y'all agree on this, I'll throw a PR in.

**Comment by jkrasting** [comment]
Good catch, @raphaeldussin!  We should delete that line from the refineDiag script.  

It is a shame that earlier versions of Numpy did not fail on this obvious error.
