### ISSUE TITLE
Configuration on CENTOS linux cluster with intel compiler and openmpi

### ISSUE THREAD

**Issue by andreasschmittner** [NOAA-GFDL/MOM6-examples#289]
Hi, I've followed the instructions (https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started) but get stuck in the step "Compiling the FMS shared code". I figured I should use the linux-intel.mk template so I tried this:

(cd build/intel/shared/repro/; rm -f path_names; ../../../../src/mkmf/bin/list_paths -l ../../../../src/FMS; ../../.
./../src/mkmf/bin/mkmf -t ../../../../src/mkmf/templates/linux-intel.mk -p libfms.a -c "-Duse_libMPI -Duse_netCDF -D
SPMD" path_names) 

Which gives a long error message starting with:

Package mpich2-f90 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpich2-f90.pc'
to the PKG_CONFIG_PATH environment variable

I don't have mpich but I do have openmpi, so how do I tell it to use openmpi instead of mpich?

Thanks,
Andreas

**Comment by marshallward** [comment]
Unfortunately we don't yet have a "smart" configuration setup such as autoconf, and that particular template file assumes (among other things) that one is using MPICH with Intel compilers.

What sort of machine are you running this on?  The `linux-ubuntu-xenial-gnu.mk` compiler is a little more generic about its MPI library and may work for you.  The flags are for GNU compilers, but you might be able to construct something suitable for your platform.

If you're on a supercomputer, then the environment's probably very custom and might need to get some local support.

We've been putting off an autoconf config, partly to see how the FMS library decides to solve the problem, but we probably ought to prioritize this.

**Comment by andreasschmittner** [comment]
I'm not on a supercomputer. It is my own linux cluster.

(base) [aschmitt@master ~]$ uname -a
Linux master 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by awallcraft** [comment]
When using the Intel Compiler, I have found the best starting point to be ncrc-intel.mk.  This is for a Cray, which has "ftn" as the mpi-aware Fortran compiler command.  Change this to the corresponding command on your system, which is often mpif90 (sometimes mpiifort).  I also change cc to (say) mpicc, but icc (i.e. the serial compiler) should also work.

**Comment by awallcraft** [comment]
If you are using the GNU compilers, ncrc-gnu.mk should work with ftn again replaced by (say) mpif90.

**Comment by andreasschmittner** [comment]
Thanks. I'm modified the ncrc-intel.mk by changing ftn to mpif90 and cc to mpicc.

Now the issues seems to be nf-config.

(base) [aschmitt@master MOM6-examples]$ (cd build/intel/shared/repro/; source ../../env; make NETCDF=3 REPRO=1 libfms.a -j)
mpif90 -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE -fpp -Wp,-w  nf-config not yet implemented for cmake builds -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -msse2            -c -I../../../../src/FMS/include -I../../../../src/FMS/mpp/include	../../../../src/FMS/mpp/mpp.F90
mpicc -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE -D__IFC  -I/home/aschmitt/miniconda3/envs/FERRET/include -sox -traceback -O2 -debug minimal -msse2            -c -I../../../../src/FMS/mosaic	../../../../src/FMS/mosaic/read_mosaic.c
mpicc -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE -D__IFC  -I/home/aschmitt/miniconda3/envs/FERRET/include -sox -traceback -O2 -debug minimal -msse2            -c	../../../../src/FMS/mpp/nsclock.c
ifort: error #10236: File not found:  'nf-config'
ifort: error #10236: File not found:  'not'
ifort: error #10236: File not found:  'yet'
ifort: error #10236: File not found:  'implemented'
ifort: error #10236: File not found:  'for'
ifort: error #10236: File not found:  'cmake'
ifort: error #10236: File not found:  'builds'
Using 8-byte addressing
Using pure routines.
Using allocatable derived type array members.
Using cray pointers.
make: *** [mpp.o] Error 1

**Comment by kshedstrom** [comment]
There was a range of netcdff versions with a broken nf-config. They said they fixed it in the current release, or you can go back to an older one.

**Comment by awallcraft** [comment]
See if stand-alone nf-config produces sensible values, and if so hardwire them in your .mk.  You want the intel version of the library if you have multiple versions.

gaffney02 191> which nf-config
/p/app/COST/netcdf-fortran/4.4.2/intel//bin/nf-config
gaffney02 192> nf-config --fflags
-I/p/app/COST/netcdf-fortran/4.4.2/intel/include
gaffney02 193> nf-config --flibs
-L/p/app/COST/netcdf-fortran/4.4.2/intel/lib -lnetcdff -L/p/app/COST/netcdf-c/4.3.3.1/intel//lib -L/p/app/COST/hdf5/1.8.15/intel//lib -lnetcdf -lnetcdf

**Comment by marshallward** [comment]
@andreasschmittner Did you make any progress on this?

**Comment by andreasschmittner** [comment]
No, I didn’t. Don’t have time right now to work on this.

**Comment by marshallward** [comment]
@andreasschmittner Just wanted to flag with you that we have an autoconf build framework set up now, which may help with the issues that you were seeing.

https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/ac/README.md

I will close this issue due to its age, but feel free to re-open.
