### ISSUE TITLE
Problem with installation, running first case.

### ISSUE THREAD

**Issue by srinivasvl81** [NOAA-GFDL/MOM6-examples#290]
This is the output when I try to install MOM6 on my laptop using this link: https://github.com/NOAA-GFDL/MOM6-examples/wiki/Ubuntu-compiler-environment

```
mpirun -np 4 ../../build/gnu/ocean_only/repro/MOM6
../../build/gnu/ocean_only/repro/MOM6: symbol lookup error: /usr/lib/libmpi_mpifh.so.12: undefined symbol: mpi_fortran_weights_empty
../../build/gnu/ocean_only/repro/MOM6: symbol lookup error: /usr/lib/libmpi_mpifh.so.12: undefined symbol: mpi_fortran_weights_empty
../../build/gnu/ocean_only/repro/MOM6: symbol lookup error: /usr/lib/libmpi_mpifh.so.12: undefined symbol: mpi_fortran_weights_empty
../../build/gnu/ocean_only/repro/MOM6: symbol lookup error: /usr/lib/libmpi_mpifh.so.12: undefined symbol: mpi_fortran_weights_empty

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 30770 RUNNING AT VLS
=   EXIT STATUS: 127
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 30771 RUNNING AT VLS
=   EXIT STATUS: 127
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 30772 RUNNING AT VLS
=   EXIT STATUS: 127
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 30773 RUNNING AT VLS
=   EXIT STATUS: 127
===================================================================================
```

Let me know, how to fix this?
Thank you.

**Comment by marshallward** [comment]
I have not seen this error, but it looks like a problem with your MPI library.  Dr Google suggests its a mixup between MPICH, which typically uses `/usr/lib/libmpi_mpifh.so`, and OpenMPI, which typically uses `/usr/lib/openmpi/libmpi_mpifh.so`.  Additionally, if I grep both libraries, then `mpi_fortran_weights_empty` is defined (via macros) in OpenMPI but does not exist in MPICH.

You could start by looking at your environment variables (e.g. `LD_LIBRARY_PATH`) and which MPI library your `mpirun` is invoking (e.g. `mpirun --version`).

Beyond that, you'll probably need support from some local admins.

**Comment by marshallward** [comment]
Closing this issue due to lack of feedback.

@srinivasvl81 You are welcome to re-open this if needed.  Also have a look at the new autoconf build instructions, which may be able to resolve some of these configuration issues.

https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/ac/README.md
