### ISSUE TITLE
How to make own grid

### ISSUE THREAD

**Issue by cshwa** [NOAA-GFDL/MOM6-examples#295]
hello~ 
I am a newbie here. 
I wonder, is there a script for grid generation ? 
How to make own grid ? 
I wanna make 1 deg resolution for globe and then i wanna make it 
more fine scales on the North Western Pacific (1/4 deg resolution). 

Thank you

**Comment by MJHarrison-GFDL** [comment]
Grid generation scripts for out global 1/4,1/2 and 1/3 configurations are contained in this repository. 

If you are interested in building a global model from scratch, we recommend using our newer grid generation tools which are contained within a separate repository [here](https://github.com/nikizadehgfdl/grid_generation)

It sounds like you are interested in a nested grid as well. Development is ongoing for this [project](https://github.com/ESMG/ESMG-configs) , but still very much a work in progress, so community support is minimal for now.

**Comment by cshwa** [comment]
Thanks for your help.

I have two questions. 

I'm so sorry for fundamental  questions.

Q 1. I want regionally more fine grid ( latitudinal and longitudinal direction ). Is there a script for it? 

I looked into https://github.com/nikizadehgfdl/grid_generation

I want to make regional varying resoultion (except nesting, it seems nesting still need some time to fix). But in this link,  Tripolar grid only have latitudinal more fine resolution option on the equator.  Is there a code for longitudinal & latitudinal refinement at the same time. 

for example, globe has 1deg x 1deg resolution but at the same time, specific region has more fine grid on the latitudinal and longitudinal direction (1/4 deg x 1/4 deg).

But upper link and https://github.com/NOAA-GFDL/FRE-NCtools have only latitudinal varying grid resolution for tripolar grid. 

Q 2. I want to make two vertical coordinate SIGMA and Z. How can I make this.

Making "Z" coordinate  is on the https://github.com/NOAA-GFDL/FRE-NCtools .
But i can't find the sigma coordinate generating scrip.
Is there a sigma coordinate generating script?

Maybe i miss something? 

Thanks for your help

**Comment by adcroft** [comment]
1. We do not have scripts that make regionally refined grids the way you describe, in particular for refined longitudinal resolution within the tri-polar grid. However, the repository @MJHarrison-GFDL pointed you to is self-contained python and I suspect would be the best place for you to start if you wanted to develop such a grid.
2. The vertical coordinate is configured at run-time. See [sigma](https://github.com/NOAA-GFDL/MOM6-examples/blob/dev/gfdl/ocean_only/flow_downslope/sigma/MOM_parameter_doc.all#L374-L416)  and  [z](https://github.com/NOAA-GFDL/MOM6-examples/blob/dev/gfdl/ocean_only/flow_downslope/z/MOM_parameter_doc.all#L374-L416) for examples.

**Comment by cshwa** [comment]
Thank you

It helped me a lot
