### ISSUE TITLE
Checksum error following restart

### ISSUE THREAD

**Issue by gmacgilchrist** [NOAA-GFDL/MOM6-examples#296]
I am attempting a restart of OM4_025.JRA from the start of 2018. I have taken a restart file from a run done by @raphaeldussin, which was performed on ~4600 cores. The restart works fine if I use the same number of cores as Raph's original. Because I am just doing relatively short runs (~1 month), I want to let run on a smaller number of nodes (someone is welcome to advise me if this is a pointless effort).

So, I combined the restart files using the FRE-NCtools `combine_restarts`, somewhat consistent with @MJHarrison-GFDL response [here](https://github.com/NOAA-GFDL/MOM6/issues/958#issue-471679073). (SIDENOTE: I actually encountered the same issue that Julius cites there in when using `mppnccombine` - it fails and returns `Error: cannot write variable "Layer"'s values!`, hence why I used `combine_restarts` instead.)

With my newly combined restart files, I try to perform this restart on 480 cores (using `mask_table.96.32x18.480`), but it returns a fatal error from MOM_restart: `Checksum of input field h F999B62F5FAC9AE7 does not match value 1919B62F5FACC28F stored in INPUT/MOM.res.nc`.

I was told that this was something to do with padding around masked regions, and the way that this is handled depending on the distribution of nodes, but I assumed that combine_restarts would handle this. Can anyone advise? Is this a MOM issue or an FMS issue?

Note that I'm running MOM6-SIS2 directly, not through an xml file.

**Comment by gmacgilchrist** [comment]
Nevermind, found the flag `RESTART_CHECKSUMS_REQUIRED = True`. Closing the issue.

**Comment by nikizadehgfdl** [comment]
Note that using that flag  is not recommended for multi-segment runs as it will remove a check that might catch I/O errors for multi-year runs. 
Instead we usually remove the checksum attributes from the recombined restart files.

Also, could you write down the exact mppnccombine command (including the input files) that produced the above error? Could you include the result of "which mppnccombine"? Thanks.

**Comment by gmacgilchrist** [comment]
That's good to know, thanks Niki. Is there a straightforward way to remove the attributes with FRE-NCtools, or another compiled software on gaea?

`which mppnccombine` returns
`/ncrc/home2/fms/local/opt/fre-nctools/bronx-15/ncrc/bin/mppnccombine`

The error arises from:
```
mppnccombine MOM.res_1.nc
Error: cannot write variable "Layer"'s values!
Error: cannot write variable "0"'s values!
Warning: output file may be incomplete!```

I also tried explicitly specifying the input files, but same error occurred.

**Comment by gmacgilchrist** [comment]
This is likely a separate issue, but perhaps related. I can open a separate issue if necessary.

The model is now crashing with 

```
diamonds, calve_icebergs: WARNING!!! Iceberg born in land cell     406
      1 -199.275852425432    -80.5701692881059
```

It doesn't actually seem to give a fatal error, it just keeps printing this warning over and over. I'm not sure what finally crashed it. This is, I believe, to do with the padding of the mask in the ice model. Is there an easy fix for this?

**Comment by nikizadehgfdl** [comment]
You can drop the checksum for all vars via
``` 
ncatted -O -a checksum,,d,, $file
```

Please point me to the location of input files  MOM.res_1.nc.*  on gaea or archive.

**Comment by nikizadehgfdl** [comment]
For the bergs issue (and probably more that you might run into) the following xml hack might help you bypass the problem. You can start from last few lines for calving.res and see if they fix your problem.

```
####################################################################################################
##The following is to avoid model crash with a layout other than the one that produced the initCond.
##The problem could occur if the generating model run used a mask_table that was different from the
##current model run. Specifically, when SIS2 reads the ice_model.res.nc it chokes on the unphysical 
##values on land on the masked pes (9.96E36) that should have been set as "missing values". 
##
if ( $currentSeg == 1 ) then
  cd $work/INPUT
  cp ice_model.res.nc ice_model.res1.nc
  #All ice restart variables should be 0 where they have a "missing value" (9.96E36)
  foreach var ( T_skin coszen rough_moist rough_heat rough_mom sym_str_s str_t str_d sym_v_ice_C sym_u_ice_C sal_ice enth_ice H_to_kg_m2 h_ice enth_snow h_snow h_pond flux_sw_nir_dif flux_sw_nir_dir flux_sw_vis_dif flux_sw_vis_dir p_surf calving_hflx runoff_hflx calving runoff fprec lprec flux_lw flux_salt flux_q flux_t flux_v flux_u )
     ncap2 -s "where( $var > 1e36) $var =0.0" ice_model.res1.nc ice_model.res2.nc
     mv -f ice_model.res2.nc ice_model.res1.nc
  end
  #except part_size that should be 1 for category 1 and 0 otherwise. But I don't know how to do that!
  #The next best guess would be 1/6 for all categories so that they add up to 1:
  ncap2 -s 'where( (part_size>1e36) ) part_size =1.0/6.0' ice_model.res1.nc ice_model.res2.nc
  cp -f ice_model.res2.nc  ice_model.res.nc

  #Same story with calving.res.nc
  cp -f calving.res.nc calving.res1.nc
  ncap2 -s 'where( stored_ice>1e36 ) stored_ice =0.0' calving.res1.nc calving.res2.nc
  mv -f calving.res2.nc calving.res1.nc
  ncap2 -s 'where( stored_heat>1e36 ) stored_heat =0.0' calving.res1.nc calving.res2.nc
  mv -f calving.res2.nc calving.res.nc
  cd $work
endif
```

**Comment by gmacgilchrist** [comment]
Thanks, Niki.

`MOM.res_1.nc.*` files are here: `/lustre/f2/dev/gfdl/Graeme.Macgilchrist/MOM6-examples/ice_ocean_SIS2/OM4_025.JRA/RESTART/`
They have been unpacked from the `20180101.tar` file.

**Comment by nikizadehgfdl** [comment]
Please use option -64 with mppnccombine, e.g., 
``` 
mppnccombine -64 MOM.res_1.nc MOM.res_1.nc.000*
```
This worked for me when I used your input files. Dropping -64 I get what you got.

**Comment by gmacgilchrist** [comment]
Thank you. Is `mppnccombine` preferable to `combine_restarts` or they leveraging the same tools?

**Comment by underwoo** [comment]
`combine_restarts` uses some logic to correctly combine restart files with the correct combine tool: `mppnccombine` for atmosphere and ocean restart files and `combine-ncc` for the land and unstructured grid files.  The options passed to `mppnccombine` in `combine_restarts` is a generic set of options that work in _most_ cases.  If you feel these options should be modified, please submit an issue to the NOAA-GFDL/FREnctools repository.
