### ISSUE TITLE
Inactivating for masking options (in MOM_input).

### ISSUE THREAD

**Issue by HyunkeunJin** [NOAA-GFDL/MOM6-examples#297]
Hi, I am trying to make the global model based on the MOM6.
It is successful to perform a numerical model continuously, but I found a problem when I checked the 3d-output.

it didn't work to activate the adopted masking options of the MOM_input as follows.

( ! === module ideal_age_example === 
COORD_CONFIG = "file"
TOPO_CONFIG = "file"
TOPO_FILE = "topog.nc" 
MAXIMUM_DEPTH = 5000.0
MINIMUM_DEPTH = 0.5
MASKING_DEPTH = 1.0 )

Both the whole layers from the surface to the bottom also have the same coastal line.   
The shallow region than the reference depth (from topog.nc) has shown an abnormally high temperature than the deep ocean region.

I am looking forward to your advice and attach a file for the temperature map at 500m depth. 
Thank you in advance. 

p.s: All restart files also have the same coastal line in whole layers.

![global_temp_non_mask](https://user-images.githubusercontent.com/41406917/72576718-d2156200-3913-11ea-8331-8451a6671337.gif)

**Comment by adcroft** [comment]
I think you are looking at native model output. The vertical coordinate system of the dynamic core is generalized and does not use "masking" in the vertical. Masking is only applied for complete columns (i.e. continental land). The diagnostics can be written out in z*-coordinates which are masked and depending on the analysis is the recommended output to use.

**Comment by HyunkeunJin** [comment]
> Thank you for your reply. Based on that I understand your advice, the masking process is performed by referring to a mask file(e.g ocean_mask.nc) when writing the output file. 
In this case, I already had prepared the masing files (ocean & atmos) before the numerical model implement. 
Maybe I'd better check the files (topog.nc & mask files) first to determine if there is an error.
