### ISSUE TITLE
Buffer size mismatch in Baltic and Baltic_ALE_z_offline_tracers cases causes crash

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MOM6-examples#305]
@marshallward @adcroft
I've been running the [gaea-ci](https://github.com/marshallward/gaea_ci) test cases for supported configurations with and without the new FMS IO. Both cases fail when compiled with Intel 18.0.6.288 and Gnu 7.3.0 with the following error:
`FATAL from PE  (any number 0--59): set_group_update: update_buffer_pos .NE. unpack_buffer_pos`

I initially opened the issue in FMS (see [#330](https://github.com/NOAA-GFDL/FMS/issues/330)), but this error occurs regardless of whether the new IO is included when using the latest code from MOM6, SIS2, FMScoupler, and FMS 2020.01, 2019.01.01 and xanadu.  As I detailed in the FMS issue (see this [reply](https://github.com/NOAA-GFDL/FMS/issues/330#issuecomment-597766889), the error occurs during initialization via a wrapped call to `set_group_update` by `MOM_dynamics_split_RK2.F90`. In some cases,  end indices used to set message sizes are larger than the start indices, and result in negative values (though the magnitudes appear to be correct), leading to the buffer size error.

Additional details:
FMS tags: [xanadu](https://github.com/NOAA-GFDL/FMS/releases/tag/xanadu), [2019.01.01](https://github.com/NOAA-GFDL/FMS/releases/tag/2019.01.01), [2020.01.01](https://github.com/NOAA-GFDL/FMS/releases/tag/2020.01)
FMScoupler: [2020.01](https://github.com/NOAA-GFDL/FMScoupler/releases/tag/2020.01)
MOM6: dev/gfdl on my [fork](https://github.com/wrongkindofdoctor/MOM6)
SIS2: dev/gfdl on my[ fork](https://github.com/wrongkindofdoctor/SIS2)
atmos_null:[ master](https://github.com/NOAA-GFDL/atmos_null)

Stack trace:
```
 00000000051982B1  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
MOM6               00000000047630EC  mpp_domains_mod_m        1929  mpp_domains_util.inc
MOM6               0000000004E6D163  mpp_domains_mod_m         471  mpp_group_update.h
MOM6               0000000002AAC3F0  mom_domains_mp_do        1102  MOM_domains.F90
MOM6               00000000008F07F7  mom_dynamics_spli        1209  MOM_dynamics_split_RK2.F90
MOM6               000000000136CCB9  mom_mp_initialize        2325  MOM.F90
MOM6               00000000012EBAA0  ocean_model_mod_m         270  ocean_model_MOM.F90
MOM6               0000000000A5BE64  coupler_main_IP_c        1793  coupler_main.F90
MOM6               0000000000A4732A  MAIN__                    612  coupler_main.F90

**Comment by marshallward** [comment]
Is this a new issue related to using new compilers (Intel 18 / GNU 7.3)?  We recently shifted our GitLab Gaea testing to 2019.01.01 and it is currently running without any errors like this.

Is there another point of difference that I could be missing here?

**Comment by wrongkindofdoctor** [comment]
Perhaps. What compilers/versions have you been testing with?

**Comment by marshallward** [comment]
Our compilers are defined in an `environs` directory of my MOM6-examples repository.  This looks like a custom component that my `Makefile` expect, but I may have forgotten to share with you. 

For example `intel.env` has
```
module unload PrgEnv-intel
module load PrgEnv-intel
module load cray-netcdf
```
so largely default Intel environments in my case.  I'll email you with my directory contents so we can get those in sync.

----

Another point of difference seems to be coupler; we are using this hash:

https://github.com/NOAA-GFDL/FMScoupler/tree/14578f09a25c8e6101faba18342630af267cdba9

Your trace points to L1226 in `MOM_dynamics_split_RK2.F90` which is a `register_diag_field` in the newer source (`dev/gfdl` for example) but the subsequent step is into a `mpp_do_group_update`, which is making it hard for me to look into it.  Can you confirm where in the RK2 timestep that you are doing the MPP call, and why it's not matching the backtrace?

Also, @nikizadehgfdl is aware of some issues related to the new coupler and new compilers, and has said he'd also try to look into this.

**Comment by wrongkindofdoctor** [comment]
The call tree is hard to map without DDT because the relevant procedures are buried in .inc and .h files in mpp/include. The relevant steps after mpp_do_group_update are:
do_group_pass
  mpp_do_group_update
    [search_update_overlap](https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/mpp/include/mpp_domains_util.inc#L891)
      [set_overlaps](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_define.inc#L4934) 
         [add_update_overlap](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_define.inc#L7920)

The last few lines of add_update_overlap are where the output message size is computed using the compute (I think) indices:
```
do n = count_out+1, count
    overlap_out%msgsize(n) = (overlap_out%ie(n)-overlap_out%is(n)+1)*(overlap_out%je(n)-overlap_out%js(n)+1)
enddo
```

Some pes have `overlap_out%je` > `overlap_out%js`, which leads to overlap_out%msgsize(n)<0

This information is passed to the update_y%recv structure referenced in the group%update structure [here]( https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_util.inc#L1905)
The group%unpack_size for instances with group%unpack_je > group%unpack_js is < 0 lead to negative unpack_buffer_pos values < 0:
`unpack_buffer_pos = unpack_buffer_pos + group%unpack_size(nunpack)*ksize`
which triggers the error  here:
` if(update_buffer_pos .NE. unpack_buffer_pos ) call mpp_error(FATAL,  "set_group_update: update_buffer_pos .NE. unpack_buffer_pos")`

As I said before, it seems like the magnitudes of `update_buffer_pos` and `unpack_buffer_pos` match in all cases.

I recommend using DDT or print statements to display the values on line [1908](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_util.inc#L1908) of mpp_domains_util.inc  if this explanation is insufficient (it's one of those cases where showing you would be better).

**Comment by marshallward** [comment]
Are you able to get a clear backtrace of the MOM side of things though?  Line 1226 of `MOM_dynamics_split_RK2` does not seem to sync with `dev/master`.  I am concerned that we're not talking about the same source code.

**Comment by wrongkindofdoctor** [comment]
It looks like my fork is a bit behind. Let me pull in the latest updates and rebuild so I can get an updated trace.

**Comment by marshallward** [comment]
I think I see the equivalent point:

https://github.com/wrongkindofdoctor/MOM6/blob/5f9b0240e5004b6fa6ca87a57db5025dde36e22d/src/core/MOM_dynamics_split_RK2.F90#L1226

It looks equivalent to L1209 in dev/gfdl.

For now I can try running the CI using Intel 18 and see if it works, and we can iterate towards a common point.

**Comment by wrongkindofdoctor** [comment]
I modified the stack trace with the result from code built using the latest dev/gfdl updates in the first message, and do_group_pass is now on line 1209 of MOM_dynamics_split_RK2.

**Comment by marshallward** [comment]
I'm having several Lustre problems on Gaea, but it looks like I was able to run the suite using Intel 18.0.8 and GCC 7.3.0, although my Intel REPRO runs did change answers (@nikizadehgfdl has commented on this already).

This would be using FMS 2019.01.01 but presumably the old IO API.

I guess the next thing to try is the updated coupler?

**Comment by wrongkindofdoctor** [comment]
Yes. Please try the[ 2020.01 release](https://github.com/NOAA-GFDL/FMScoupler/releases/tag/2020.01) of FMScoupler.

**Comment by nikizadehgfdl** [comment]
@marshallward note that if you use -xsse2 instead of -msse2 compiler switch for Intel18 it will reproduce Intel16.

**Comment by marshallward** [comment]
Thanks @nikizadehgfdl I'll swap over.

(Surprised that -x in place of -m fixes it rather than using -m in place of -x, but we can chat about that another time!)

**Comment by wrongkindofdoctor** [comment]
I'm STILL getting the same crash even with the old coupler running on 60 pes via an interactive session.  I'm running the debug dynamic-symmetric executable built with intel 18.0.8.  All of my tags seem to match the ones @marshallward is using. I'll try submitting this as a batch job. If that still fails, I'm going to move on to the other tests that will work with the new IO because I have no idea what's going on.

**Comment by nikizadehgfdl** [comment]
I reproduced this. Has nothing to do with Intel18 or 2020.01 FMS (happens with Intel16 and xanadu FMS too). Any number of cores larger than 8 causes it. I think the physical domain of this test is so small that domain decomposition goes bad for n>8. I don't know why but I bet @Hallberg-NOAA knows. @wrongkindofdoctor  could you try srun -n 8 and see if you run into the same issues?

**Comment by marshallward** [comment]
Thanks @nikizadehgfdl 

My Baltic is set up to only run on 2 cpus.  @wrongkindofdoctor did you change this, or was it a script malfunction?

**Comment by wrongkindofdoctor** [comment]
No, I misinterpreted the run reqs; the OM4 tests I started running prior require more cpus. I'll try again with -n 2.

**Comment by wrongkindofdoctor** [comment]
Yup, that seems to have done the trick. Thanks @marshallward and @nikizadehgfdl !

**Comment by wrongkindofdoctor** [comment]
> I think the physical domain of this test is so small that domain decomposition goes bad for n>8. I don't kno
