### ISSUE TITLE
Relocation of MOM6/SIS2 repositories

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6-examples#31]
The locations of the various MOM6 and SIS2 repositories will soon be moved from the GitHub organization "CommerceGov" to the GitHub organization "NOAA-GFDL". They will all still be on GitHub but at a new URL.

## What's changing?

The four existing repositories will have new locations and names as follows:
- `CommerceGov/NOAA-GFDL-MOM6-examples` -> `NOAA-GFDL/MOM6-examples`
- `CommerceGov/NOAA-GFDL-MOM6` -> `NOAA-GFDL/MOM6`
- `CommerceGov/NOAA-GFDL-SIS2` -> `NOAA-GFDL/SIS2`
- `CommerceGov/NOAA-GFDL-FMS` -> `NOAA-GFDL/FMS`

Note that the repository names will be shorter as a result of the move.

In addition, the new locations will be publicly visible whereas the current repositories are private and only visible by invitation.

## Why move?

The GitHub organization "CommerceGov" was setup my the CIO of the Department of Commerce (DOC) which allowed us to experiment with using GitHub for our code projects. Since then, DOC has formulated [guidance](https://github.com/CommerceGov/Policies-and-Guidance/blob/master/GithubGuidanceforDepartmentofCommerce.md#department-of-commerce-accounts-on-github) that i) only requires DOC-wide projects to reside under "CommerceGov" and ii) allows NOAA/GFDL to collect and manage it's own repositories using it's own GitHub account "NOAA-GFDL". Keeping our repositories under the "CommerceGov" organization no longer makes sense, especially since we envision more repositories moving to GitHub.

## Why public repositories?

1. We always intended to switch to an open-source model. When to do so was mostly a matter of convenience.
1. Making a repository visible does not constitute a public release - meaning a sanctioned and supported version of the codes. We are still in development mode and not ready to support a public release.
1. The private aspect of our repositories has occasionally been an annoyance, for example, when trying to quickly share something with someone who is not on the access list.

## How will this affect you?

1. This move should not break anything. GitHub will re-direct all URLs for you so, as far as we understand things, everything should continue to work as if nothing had changed.
1. Your forks will become public. If you have any commits on your forks that you would rather not have made public then you should make a local clone of your fork and then delete the fork on GitHub.
1. Some boiler plate (README's with legal parts) will be updated.
1. Once the move has taken place, we will send instructions on how to update your URLs, even though it is not technically necessary to update URLs.

## When?

Sometime in the next few weeks.

**Comment by adcroft-gfdl** [comment]
Don't panic - your forked repositories are still there.

When the repositories were moved to https://github.com/NOAA-GFDL they became public and GitHub sensibly did not make your forks public without your consent. Simply visit the the front-page of your fork (at https://github.com), read the message, go to settings for the fork and "Make public".

**Comment by StephenGriffies** [comment]
Will new code committed to Git at GFDL be placed onto the NOAA-GFDL repository?  

Will the older Commerce repository be frozen, and eventually removed?

**Comment by adcroft-gfdl** [comment]
@StephenGriffies  The NOAA-GFDL/* repos and CommerceGov/NOAA-GFDl-* repos are one and the same - they are effectively just aliases of each other. Committing to the old URL will still work. No procedures have to be changed.

I don't know if the aliases ever expire but all instructions have been updated to use the new URLs so I hope that by the time they expire they will have been forgotten.
