### ISSUE TITLE
OM4_025 experiment crashes in horiz_interp during initialization

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MOM6-examples#312]
@marshallward @nikizadehgfdl
**Describe the bug**
The MOM6 [OM4_025 experiment](../../build/intel/debug/dynamic/ice_ocean_SIS2/MOM6) crashes with the following error in [horiz_interp_bilinear::find_neighbor](https://github.com/wrongkindofdoctor/FMS/blob/ba224d60fb82d9b64698f3d45bcfb77dee745e7f/horiz_interp/horiz_interp_bilinear.F90#L475) (I've included the data dumped to the output log prior to the error):
```
lon,lat=   639.000000000000        999.000000000000     
 npts=        1796
 is,ie=           71          69
 js,je=            1         181
 lon_in(is,js)=  -109.500000000000     
 lon_in(ie,js)=  -111.500000000000     
 lat_in(is,js)=  -89.5000000000000     
 lat_in(ie,js)=  -89.5000000000000     
 lon_in(is,je)=  -109.500000000000     
 lon_in(ie,je)=  -111.500000000000     
 lat_in(is,je)=   90.0000000000000     
 lat_in(ie,je)=   90.0000000000000    
FATAL from PE   128: find_neighbor: the destination point is not inside the source grid
```

**To Reproduce**
* Clone the MOM6-examples repo, FMS (xanadu, 2020.01, 2020.02, or 2020.03-alpha1), FMScoupler (2020.02) MOM6 (dev/gfdl), and SIS2 (dev/gfdl)
* compile the executable with intel 18.0.6.288 in debug mode on Gaea
* cd to MOM6-examples/ice_ocean_SIS2/OM4_025 and run the executable with 480 pes

**Expected behavior**
The run does not crash
**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Intel 18.0.6.288
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI): Cray MPI
- netCDF Version: For both C and Fortran: C: 4.4.0, Fortran: 4.2.0
- Configure options: Any additional flags, or macros passed to configure: debug

**Additional context**
* Replicating the issue is easier if you copy the working directory I have on gaea. I will forward paths and details offline if necessary.
* The default setup for this experiment uses the mask table mask_table.96.32x18
* The IO layout is 2,2
* I'm tagging @GFDL-Eric in case this is an FMS issue

stack trace:
```
MOM6               0000000004DC7954  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
MOM6               00000000058573C0  horiz_interp_bili         706  horiz_interp_bilinear.F90
MOM6               0000000005843EBB  horiz_interp_bili         344  horiz_interp_bilinear.F90
MOM6               000000000550B7E4  horiz_interp_mod_         599  horiz_interp.F90
MOM6               0000000002C19E86  mom_horizontal_re         549  MOM_horizontal_regridding.F90
MOM6               0000000002FBC7EB  mom_state_initial        2182  MOM_state_initialization.F90
MOM6               0000000002F3D9E2  mom_state_initial         240  MOM_state_initialization.F90
MOM6               00000000017D2306  mom_mp_initialize        2396  MOM.F90
MOM6               0000000003999900  ocean_model_mod_m         271  ocean_model_MOM.F90
MOM6               000000000164D784  coupler_main_IP_c        1793  coupler_main.F90
MOM6               0000000001638C4A  MAIN__                    612  coupler_main.F90
```

**Comment by MJHarrison-GFDL** [comment]
This works with intel16 using this PE count and the default FMS repo for MOM6-examples. The target lat/lon are bad (999,639 respectively). Is this an intel18 problem or a FMS2 problem?

**Comment by marshallward** [comment]
I've run everything under Intel 18 using FMS 2019.01.01 (close enough to xanadu?) and whatever coupler is set, and things seems to be working.  Do you know what is different here?  I do get different answers on some tests with DEBUG and REPRO (a known issue) but both run for me.

I have not tried Coupler 2020.02, could that be the issue here?

**Comment by wrongkindofdoctor** [comment]
I pulled in some updates to the MOM6-examples, recompiled, and this seems to have resolved the problem.
