### ISSUE TITLE
MLE_FRONT_LENGTH in ice_ocean_SIS2 OM4_025 vs OM4_05

### ISSUE THREAD

**Issue by jlpearso** [NOAA-GFDL/MOM6-examples#339]
Hello,
  I am wondering if someone could help me understand why the parameters are set as such:

In OM4_05 MOM_input: MLE_FRONT_LENGTH = 200.0
In OM4_025 MOM_input: MLE_FRONT_LENGTH = 500.0

I expected OM4_05 to be larger, say 2km. Is there something I am missing with the way this is implemented? Or was this tuned/adjusted for stability?

New to MOM6 so any explanation you can provide would be helpful. Thank you!

**Comment by adcroft** [comment]
Section [2.2.2](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019MS001726#jame20966-sec-0020) of the [OM4 paper](https://doi.org/10.1029/2019MS001726) describes how MLE works and was developed. Quote: "...we found a strong sensitivity of SST biases to the MLE parameterization parameters, with the frontal length the most efficient parameter found to optimize for reducing biases. Hence, the OM4p25 and OM4p5 models use different frontal lengths (see [Table 2](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019MS001726#jame20966-tbl-0002))." While we had hoped to use the "resolution aware" aspect of the MLE parameterization, in the end the biases required us to tune OM4_05 and OM4_025 independently. The experiments in Table 2 lists experiment configurations that connect the two end-points of OM4_05 and OM4_025.

**Comment by jlpearso** [comment]
Ah, thank you!
