### ISSUE TITLE
request for MOM6 with biogeochmistry

### ISSUE THREAD

**Issue by devasena1964** [NOAA-GFDL/MOM6-examples#347]
Dear Developers

can I download MOM6 code embedded with bio geochemistry code for testing (either COBALT or MOM_SIS_TOPAZ)
I am unable to find in the MOM6 examples about biogeochemistry.
Kalyani

**Comment by marshallward** [comment]
I believe you are looking for this repository:

https://github.com/NOAA-GFDL/ocean_BGC

which hosts several of GFDL's BGC models.

These are not maintained as part of MOM6 but can be provided as "externals" in the [`config_src/external/GFDL_ocean_BGC`](https://github.com/NOAA-GFDL/MOM6/tree/dev/gfdl/config_src/external/GFDL_ocean_BGC) directory.

I have not run with the BGC before, but I believe that MOM6 contains the interface to the tracers, whereas the code in ocean_BGC repository implements the tracers.

For example, this is a stub for the `generic_tracer` code in MOM6:

https://github.com/NOAA-GFDL/MOM6/blob/12f29f67abdc6a8afb783e50159b1d9ffe014692/config_src/external/GFDL_ocean_BGC/generic_tracer.F90

which would be replaced by this file in ocean_BGC:

https://github.com/NOAA-GFDL/ocean_BGC/blob/master/generic_tracers/generic_tracer.F90

As usual, you may be able to get more targeted advice at the MOM6 forums: https://bb.cgd.ucar.edu/cesm/forums/mom6.148/

**Comment by devasena1964** [comment]
Dear Dr Marshallward
Thank you very much, I will explore the code
Regards
Kalyani
