### ISSUE TITLE
Fix the wiki (which I broke...)

### ISSUE THREAD

**Issue by hdrake** [NOAA-GFDL/MOM6-examples#351]
I (ironically) somehow accidentally wiped out the "How to contribute" section of the Wiki and it seems there is no way to revert that kind of change from within the browser.

There is no way to create a pull request for the Wiki, so could someone with the proper permissions please merge the fixed Wiki from my branch (https://github.com/hdrake/MOM6-examples.wiki.git) into the NOAA-GFDL branch?

**Comment by marshallward** [comment]
Looks like you may have deleted then recreated the file.  I will look into it.

**Comment by hdrake** [comment]
Yes, I think that is what I did. I was able to revert the changes on my own fork using the command line (see link above).

**Comment by marshallward** [comment]
I just replaced `How-to-Contribute.md` with `Updating-broken-links-to-open-source-guides.md`.  Does it look OK?

**Comment by hdrake** [comment]
>Does it look OK?
Yes, looks great—thank you!
