### ISSUE TITLE
Error during  OM4_05  running

### ISSUE THREAD

**Issue by ranjit02** [NOAA-GFDL/MOM6-examples#356]
I am running the MOM6 with ice-ocean-sis2 for OM4_05 data set, I followed the all installation instructions which are mention on https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#downloading-input-data
but still getting below error, Please help me with this.

![image](https://user-images.githubusercontent.com/59292502/182144036-40459913-15b7-4a52-807b-547f7dbacebd.png)

Thanks,
Ranjit

**Comment by marshallward** [comment]
Most likely you do not have a directory named `RESTART/` in your `OM4_05` directory.   Many of the models in this repository assume that this directory must exist.

This is more of an FMS or GFDL coupler requirement, than a MOM6 issue, although we could perhaps do more to help here.
 
Unfortunately git does not track empty directories, but we may be able to address it by adding a `RESTART/` directory with an empty text file.  We could also contact the coupler developers to find a more user-friendly solution.

**Comment by ranjit02** [comment]
Thanks marshallward, It's working now.
