### ISSUE TITLE
ISOMIP Configuration

### ISSUE THREAD

**Issue by claireyung** [NOAA-GFDL/MOM6-examples#360]
Hi folks,
I'm trying to run the MOM6 ISOMIP configurations you have in this repo. I was wondering if anyone would be able to share or point me to where I can find the ice thickness file `Ocean1_3D.nc`?
Many thanks

**Comment by marshallward** [comment]
Hi @claireyung, I followed up with people here and it looks like @Hallberg-NOAA has a copy of this file.  We are currently trying to decide whether to add it to the `.datasets` tarball or just into the repository itself.  The file itself is not large (I think around 100 kB).

In the meantime, if you contact him directly then he may be able to provide it.

**Comment by claireyung** [comment]
Thank you @marshallward!

**Comment by marshallward** [comment]
Probably resolved, but please update if there were any issues with `.datasets`.
