### ISSUE TITLE
Compiling SIS2 coupled model, missing mct_mod

### ISSUE THREAD

**Issue by markyoder** [NOAA-GFDL/MOM6-examples#362]
When compiling MOM6-SIS2 coupled model, as per these directions:

Getting this compiler error:
```
/scratch/users/myoder96/MOM6/MOM6-examples/src/MOM6/config_src/drivers/mct_cap/ocn_cpl_indices.F90:3:7:

    3 |   use mct_mod,              only: mct_avect_init, mct_avect_indexra, mct_aVect_clean, mct_aVect
      |       1
Fatal Error: Cannot open module file ‘mct_mod.mod’ for reading at (1): No such file or directory
```

Indeed, `ocn_cpl_indices.F90` definitely asks for `mct_mod` (ie, mct_mod.mod file), which I cannot find.

MCT appears to refer to "Model Coupling Toolkit;" I found an acknowledgement to this ANL project:
[https://github.com/MCSclimate/MCT](https://github.com/MCSclimate/MCT), but it looks like `mct_mod.mod` is probably derived on that work (based on the reference).

So is there another sub-project to build for MCT, or maybe those functions have moved?

**Comment by marshallward** [comment]
Which coupled model are you building?  If you are following the directions [here](https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#compiling-the-models) then you would have selected `config_src/drivers/FMS_cap` (the GFDL coupler) rather than `config_src/drivers/mct_cap` when using `list_paths`.

If you are using an MCT-based model, then you probably want to contact one of those groups.  You can try the MOM6 forums:

https://bb.cgd.ucar.edu/cesm/forums/mom6.148/

**Comment by marshallward** [comment]
Most likely something has happened with the `list_paths` command.  It could be similar to the issues you were seeing in #350.  My guess is that one of the command-line paths is getting mangled somehow and causing `drivers/mct_cap` to slip into `path_names`.  Unfortunately it might take a bit of troubleshooting to know the reason.  Worst case, you could just remove the lines from `path_names`.

The `mkmf` and `list_paths` tools are starting to show their age, and are even been phased out in some places.  But it's still the canonical method for building the model at GFDL, so the instructions still focus on it.

Please do post your issue in the forums, I think it could be useful to hear feedback from others.

**Comment by jiandewang** [comment]
my gut feeling is that you are having a typo or continuation line issue. Here I put a simple script that I used for compiling using mkmf
https://www.emc.ncep.noaa.gov/gc_wmb/wd20xw/JD/compile-MOM6.txt (you need to rename it to *sh, somehow our serve doesn't like *sh files). Put this file inside MOM6-examples directory. 
The usage is: compile-MOM6.sh --platform xxx, here xxx refer to the compiling option file you are going to select from mkmf/templates, for example, if you plan to use nccs-intel.mk, then xxx=nccs

**Comment by adcroft** [comment]
`${MOM6_SRC}/{*,*/*}/` is capturing all of `config_src/` . I think you want `${MOM6_SRC}/src/{*,*/*}/`

**Comment by markyoder** [comment]
Yes, I realized that after Marshall’s last comment. Thanks to both of you
***@***.*** and @Marshall) for the feedback; it was very helpful. I think
I have it sorted out.

Thanks again!

m
