### ISSUE TITLE
An error when compiling MOM6 with SIS2

### ISSUE THREAD

**Issue by liu-ran** [NOAA-GFDL/MOM6-examples#368]
An error when compiling MOM6 with SIS2 as shown in the screenshot. FMS seems to have a problem with NETCDF from this screenshot. However, I'm sure FMS has been successfully compiled because ocean_only can run with the FMS correctly. Is there any experience with this situation? Many thanks!

![image](https://user-images.githubusercontent.com/48266323/208911577-197e36c4-6e77-4360-ba9c-027c6fba4f93.png)

**Comment by marshallward** [comment]
It's looking for functions in the netCDF C library.  We don't explicitly call this function, but the circumstances around your system may require explict links to it. 

Try adding `-lnetcdf` to your Fortran flags.

**Comment by marshallward** [comment]
No feedback from user, so assuming they were able to sort this out.  Closing.
