### ISSUE TITLE
Datasets for examples

### ISSUE THREAD

**Issue by pittwolfe** [NOAA-GFDL/MOM6-examples#38]
The "Getting Started" wiki currently only gives instructions for downloading the input datasets from Gaea. I'm trying to set up a new experiment loosely based on the MESO example, but I have little previous experience with GOLD or MOM6. I was hoping I could use the MESO inputs as a template to help me figure out how to format these files.

Is there any way to download these datasets from outside of GFDL?

Christopher Pitt Wolfe

**Comment by adcroft** [comment]
I've put it in a tar file at ftp://ftp.gfdl.noaa.gov/pub/aja/MESO_025_63L.v2011.11.22.tgz

Under INPUT/ are symbolic links to the files in this tar file. You can either replace the links with these files or redirect the links to wherever you unpack the tar file.
