### ISSUE TITLE
double_gyre: xh and xq not being written correctly to prog__0001_006.nc

### ISSUE THREAD

**Issue by suyash309** [NOAA-GFDL/MOM6-examples#39]
I ran the double_gyre example and all the variables in prog__001_006.nc seem appropriate except xh and xq. 

ncdump -v xh prog_001_006.nc gives: 
xh = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21.75 ;

ncdump -v xq prog_001_006.nc gives: 
 xq = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22 ;

If I run the experiment with a cartesian grid instead of spherical, this issue does not arise. I was able to recreate this behavior on two different machines. I would be glad to share more information if required.

**Comment by adcroft** [comment]
I can reproduce this problem - somewhat surprised we have such a glaring bug!

I've traced the issue to lines [1044-1049](https://github.com/NOAA-GFDL/MOM6/commit/d64dc201f3d1acd0a43b0c358fb99aea3f23438a#diff-7282863d4534a3881e805be06279ea48R1044) in the "spherical" grid generation, which only affects a few tests. There is a typo in the loop ranges. I'll patch it shortly.

**Comment by adcroft** [comment]
Done. Thanks for the bug report, @suyash309 .
