### ISSUE TITLE
Wiki datasets on gaea are pointing to f2

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/MOM6-examples#449]
The datasets that are on gaea are still pointing to f2.  Is there an updated wiki that shows their location on f5?

https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#linking-data-sets-on-gaea

**Comment by marshallward** [comment]
Thanks Tom, I have replaced any mentions of F2 with F5 in the docs.
