### ISSUE TITLE
spurious river runoff in OM4 

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#45]
The river runoff used in this test case is spurious.  It is being interpolated at runtime from GOLD-SIS 1degree ruoff on tripolar grid.  This is wrong. 

--we cannot use the regrid online to get rivers remapped.  Instead, we need to do the regridding offline, before the simulation.
--we need to do the river regrid from the raw NCAR Dai/Trenberth data, using river regrid onto the OM4 grid.  

We can make a 12-month climatology using the IAF regridded rivers now being used by Amy Langenhorst in her OM4-IAF simulations.  She did things properly.  We need to provide a well defined sequence of steps to clean up this process of getting the river data onto OM4.

**Comment by jkbk2004** [comment]
@adcroft @StephenGriffies I am working for NCEP-EMC. Is a river runoff file available for MOM6-1deg?
