### ISSUE TITLE
MIXEDLAYER_RESTRAT = True + BULKMIXEDLAYER = False.

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#57]
The following is in OM4_025 MOM_parameter_doc.all

BULKMIXEDLAYER = False ! [Boolean] default = True

MIXEDLAYER_RESTRAT = True       !   [Boolean] default = False
                                ! If true, a density-gradient dependent re-stratifying
                                ! flow is imposed in the mixed layer.
                                ! This is only used if BULKMIXEDLAYER is true.

So are we using MIXEDLAYER_RESTRAT, even though BULKMIXEDLAYER = False?  

If we are in fact using MIXEDLAYER_RESTRAT, then the comment in the code should be corrected.  It is very confusing.

**Comment by MJHarrison-GFDL** [comment]
BULKMIXEDLAYER turns on the bulk energetic boundary layer code used in GOLD.  As opposed to the EPBL scheme.

**Comment by StephenGriffies** [comment]
My question relates to whether we should remove the noted comment in the mixed layer restratification code.

**Comment by StephenGriffies** [comment]
Thanks.
