### ISSUE TITLE
ocean_static.nc from diag_manager has holes in coordinates when using mask_table

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6-examples#70]
Since we are running with mask_table most of the time the file produced by diag_manager has holes in coordinates (geolon,gelolat) most of the time and is useless to ferret or python analysis scripts that generate figures.
 
Should it be replaced by the corrected file that patches the holes before ending up in the archives/history ?

**Comment by Zhi-Liang** [comment]
Hi Niki,

  Amy is going to update fre to replace those static fields in the
post-processing step to fix this issue.

Greetings,

Zhi

**Comment by adcroft** [comment]
The holes in coordinates are being handled at the FRE level by replacing ocean_static.nc with a pre-processed version.
