### ISSUE TITLE
ocean analysis scripts do not work for 1/2 degree models

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6-examples#77]
The ocean analysis scripts were made for 1/4 degree ocean models and they are not working for 1/2 degree models.
E.g., see
```
/home/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/gfdl.ncrc3-intel15-prod-openmp/scripts/analysis/ocn_monthly.frepp.0001-0005.printout


/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/MLD_003.py -g /archive/gold/datasets/OM4_025/mosaic.v20140610.unpacked -o /nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/ocean_0001-0005/Hosoda_MLD -l 0001-0005 /archive/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/gfdl.ncrc3-intel15-prod-openmp/pp/ocean_monthly/ts/monthly/5yr//ocean_monthly.000101-000512.MLD_003.nc
/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py:561: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1080 but corresponding boolean dimension is 576
  if not numpy.ma.getmask(s).any()==numpy.ma.nomask: weight[s.mask] = 0.
Traceback (most recent call last):
  File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/MLD_003.py", line 56, in <module>
    save=cmdLineArgs.outdir+'/MLD_003_minimum.png')
  File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py", line 67, in xyplot
    sMin, sMax, sMean, sStd, sRMS = myStats(maskedField, area, debug=debug)
  File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py", line 566, in myStats
    mean = numpy.ma.sum(weight*s)/sumArea
  File "/usr/local/python/2.7.3/lib/python2.7/site-packages/numpy-1.11.0b3-py2.7-linux-x86_64.egg/numpy/ma/core.py", line 3945, in __rmul__
    return multiply(other, self)
  File "/usr/local/python/2.7.3/lib/python2.7/site-packages/numpy-1.11.0b3-py2.7-linux-x86_64.egg/numpy/ma/core.py", line 966, in __call__
    result = self.f(da, db, *args, **kwargs)
ValueError: operands could not be broadcast together with shapes (1080,1440) (576,720)

```

**Comment by jkrasting** [comment]
There are working .frepp files in the OM4_05 examples directory.  If you
change the XML to point to them, the analysis figures will be generated.

On Wednesday, March 30, 2016, Niki Zadeh <notifications@github.com> wrote:

> The ocean analysis scripts were made for 1/4 degree ocean models and they
> are not working for 1/2 degree models.
> E.g., see
>
> /home/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/gfdl.ncrc3-intel15-prod-openmp/scripts/analysis/ocn_monthly.frepp.0001-0005.printout
>
>
> /nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/MLD_003.py -g /archive/gold/datasets/OM4_025/mosaic.v20140610.unpacked -o /nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/ocean_0001-0005/Hosoda_MLD -l 0001-0005 /archive/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/gfdl.ncrc3-intel15-prod-openmp/pp/ocean_monthly/ts/monthly/5yr//ocean_monthly.000101-000512.MLD_003.nc
> /nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py:561: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1080 but corresponding boolean dimension is 576
>   if not numpy.ma.getmask(s).any()==numpy.ma.nomask: weight[s.mask] = 0.
> Traceback (most recent call last):
>   File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/MLD_003.py", line 56, in <module>
>     save=cmdLineArgs.outdir+'/MLD_003_minimum.png')
>   File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py", line 67, in xyplot
>     sMin, sMax, sMean, sStd, sRMS = myStats(maskedField, area, debug=debug)
>   File "/nbhome/Amy.Langenhorst/ulm_201510_awg_v20160212_mom6_2016.03.22/CM4_c96L32_am4g9_fullaero_2000_t1_OMp5_lmix_H5_nmle_ndiff_meke/mom6/tools/analysis/m6plot.py", line 566, in myStats
>     mean = numpy.ma.sum(weight*s)/sumArea
>   File "/usr/local/python/2.7.3/lib/python2.7/site-packages/numpy-1.11.0b3-py2.7-linux-x86_64.egg/numpy/ma/core.py", line 3945, in __rmul__
>     return multiply(other, self)
>   File "/usr/local/python/2.7.3/lib/python2.7/site-packages/numpy-1.11.0b3-py2.7-linux-x86_64.egg/numpy/ma/core.py", line 966, in __call__
>     result = self.f(da, db, *args, **kwargs)
> ValueError: operands could not be broadcast together with shapes (1080,1440) (576,720)
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6-examples/issues/77>
>


-- 
-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by nikizadehgfdl** [comment]
John is right. They worked when I changed the xml to use OM4_05 examples directory.
