### ISSUE TITLE
poleward_heat_transport.py and  TS_depth_integrals.py fail for 1/2 degree models

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6-examples#81]
From Bill's experiment
~Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/gfdl.ncrc3-intel15-prod-openmp/scripts/analysis/ocn_annual.frepp.0001-0005.printout

```
/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/poleward_heat_transport.py -g /archive/gold/datasets/OM4_05/mosaic.v20151203.unpacked -o /nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/ocean_0001-0005/heat_transport -l 0001-0005 /archive/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/gfdl.ncrc3-intel15-prod-openmp/pp/ocean_annual/av/annual_5yr//ocean_annual.0001-0005.ann.nc
/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/poleward_heat_transport.py:66: UserWarning: Diffusive temperature term not found. This will result in an underestimation of the heat transport.
  warnings.warn('Diffusive temperature term not found. This will result in an underestimation of the heat transport.')
/usr/local/python/2.7.3/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/poleward_heat_transport.py:74: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if vmask != None: HT = HT*vmask
mkdir -p /nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/ocean_0001-0005/heat_salt_0_300m

/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/TS_depth_integrals.py -r /archive/gold/datasets/OM4_05/obs/WOA05_ptemp_salt_annual.v2015.12.03.nc -s 0 -e 300 -g /archive/gold/datasets/OM4_05/mosaic.v20151203.unpacked -o /nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/ocean_0001-0005/heat_salt_0_300m -l 0001-0005 /archive/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/gfdl.ncrc3-intel15-prod-openmp/pp/ocean_annual/av/annual_5yr//ocean_annual.0001-0005.ann.nc
 Variable named temp does not exist in file named /archive/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/gfdl.ncrc3-intel15-prod-openmp/pp/ocean_annual/av/annual_5yr//ocean_annual.0001-0005.ann.nc
         Aborting ...
Traceback (most recent call last):
  File "/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/TS_depth_integrals.py", line 41, in <module>
```

**Comment by jkrasting** [comment]
Is this still an open issue?

The poleward_heat_transport.py output looks normal.  We are not saving out
the T_diffy_2d yet, so the warning about missing the diffusive component of
the transport is to be expected.

The second error is that the script cannot find the 'temp' variable.  Other
m6 plot scripts conductive a search for the variable based on both GFDL and
CMOR names, temp vs. thetao.  This script should be rewritten to do a
similar search.

  File
"/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/analysis/TS_depth_integrals.py",
line 41, in <module>

S=state(path_ann,grid=grid,fields=['temp','salt'],interfaces='e',verbose=False)
  File
"/nbhome/Bill.Hurlin/ulm_201510_awg_v20160406_mom6_2016.03.22/CM4_c96L32_am4g9_2000_fullaero_sedi_t1_OMp5_lmix_H5_nmle_ndiff_meke.2016.03.22/mom6/tools/python/local/lib/python/midas/rectgrid.py",
line 808, in __init__
    self.variables[v] = self.rootgrp.variables[v]  # netCDF4 variable object
KeyError: 'temp'
rm: No match.

JK

-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by MJHarrison-GFDL** [comment]
Looks like 'temp' and 'salt' need to be changed to CMIP names. How do I get
there on Git?

Matt

**Comment by jkrasting** [comment]
https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/master/tools/analysis

It would be better, in my opinion, to have the script support both GFDL and
CMOR names.

JK

-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by adcroft** [comment]
Bump?

**Comment by MJHarrison-GFDL** [comment]
Closed by

https://github.com/NOAA-GFDL/MOM6-examples/commit/72af50b181fa5c26c909a9c56f519cf61f819a6e
