### ISSUE TITLE
mkmf MOM6 issue with make clean

### ISSUE THREAD

**Issue by marshallward** [NOAA-GFDL/MOM6-examples#92]
When I follow the wiki and run `mkmf` using this command:

    ../../../../src/mkmf/bin/mkmf -t ../../../../src/mkmf/templates/ncrc-intel.mk -o '-I../../shared/repro' -p 'MOM6 -L../../shared/repro -lfms' -c '-Duse_libMPI -Duse_netCDF -DSPMD -DUSE_LOG_DIAG_FIELD_INFO' path_names

it is putting the `-p` flag contents into my `make clean` rule:

    clean: neat                                                                     
        -rm -f .MOM6 -L../../shared/repro -lfms.cppdefs $(OBJ) MOM6 -L../../shared/repro -lfms

which causes `make clean` to fail.  (Not sure where the `cppdefs` part is coming from.)

**Comment by adcroft** [comment]
Yes, and I'm guilty. It's because I'm abusing "-p" option in order to get some link-time options into the target for MOM6. @jkrasting  calls it an "insertion attack" :)  And it comes about because I was trying to save compile-time by building an fms library. To do things properly mkmf needs and equivalent of "-o" for linking. I'll go talk to the mkmf powers about how to fix this...

**Comment by underwoo** [comment]
mkmf has been updated to version [19.2.0](https://github.com/NOAA-GFDL/mkmf/tree/v19.2.0) to have a `-l <linkflags>` option.  `<linkflags>` is a string of link flags that will be included on the link command in the Makefile.

**Comment by adcroft** [comment]
Thanks @underwoo . I've updated the wiki page isntructions in which I just noticed a comment about the [work around](https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#comments).

For the record, the "clean" target now looks like this for me:
```
clean: neat
        -rm -f .MOM6.cppdefs $(OBJ) MOM6
```

**Comment by adcroft** [comment]
Incase anyone doesn't remember how to update submodules, if after issueing:
```
cd MOM6-examples
git pull
git status
```

you see
> ```
> On branch dev/master
> Your branch is up-to-date with 'origin/dev/master'.
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
>   (commit or discard the untracked or modified content in submodules)
> 
> 	modified:   src/mkmf (new commits)
> ```

then you need to issue
```
git submodule update src/mkmf
```

**Comment by marshallward** [comment]
`make clean` works for me now, thanks Alistair :)
